/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ForOrganisationsRouteImport } from './routes/for-organisations'
import { Route as ForCoachesRouteImport } from './routes/for-coaches'
import { Route as IndexRouteImport } from './routes/index'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ForOrganisationsRoute = ForOrganisationsRouteImport.update({
  id: '/for-organisations',
  path: '/for-organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCoachesRoute = ForCoachesRouteImport.update({
  id: '/for-coaches',
  path: '/for-coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-coaches': typeof ForCoachesRoute
  '/for-organisations': typeof ForOrganisationsRoute
  '/insights': typeof InsightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-coaches': typeof ForCoachesRoute
  '/for-organisations': typeof ForOrganisationsRoute
  '/insights': typeof InsightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/for-coaches': typeof ForCoachesRoute
  '/for-organisations': typeof ForOrganisationsRoute
  '/insights': typeof InsightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/for-coaches' | '/for-organisations' | '/insights'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/for-coaches' | '/for-organisations' | '/insights'
  id: '__root__' | '/' | '/for-coaches' | '/for-organisations' | '/insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForCoachesRoute: typeof ForCoachesRoute
  ForOrganisationsRoute: typeof ForOrganisationsRoute
  InsightsRoute: typeof InsightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-organisations': {
      id: '/for-organisations'
      path: '/for-organisations'
      fullPath: '/for-organisations'
      preLoaderRoute: typeof ForOrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-coaches': {
      id: '/for-coaches'
      path: '/for-coaches'
      fullPath: '/for-coaches'
      preLoaderRoute: typeof ForCoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForCoachesRoute: ForCoachesRoute,
  ForOrganisationsRoute: ForOrganisationsRoute,
  InsightsRoute: InsightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
